
server:
  port: 9001

spring:
  application:
    name: sms-admin-application
  cloud:
    config:
      server:
        discovery:
          enabled: true
          serviceId: sms-config-server
        fail-fast: true
        retry:
          initialInterval: 2000
          maxAttempts: 30
#  mvc:
#    servlet:
#      load-on-startup: 1



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registryFetchIntervalSeconds: 1
  instance:
    leaseRenewalIntervalInSeconds: 1
#spring:
#  application:
#    name: spring-cloud-eureka-client
#server:
#  port: 9001
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#  instance:
#    preferIpAddress: true