

spring:
  application:
    name: sms-admin-application

  cloud:
    config:
      uri: http://localhost:7000

#          enabled: true
#          serviceId: sms-config-server

#  mvc:
#    servlet:
#      load-on-startup: 1



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registryFetchIntervalSeconds: 1
  instance:
    leaseRenewalIntervalInSeconds: 1
